// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWIX7YUUl6HxtxIQQInuPTgbxgLtk0tAQ',
    appId: '1:16569379979:web:776492347f5102642c388e',
    messagingSenderId: '16569379979',
    projectId: 'aqsa-b0bd2',
    authDomain: 'aqsa-b0bd2.firebaseapp.com',
    storageBucket: 'aqsa-b0bd2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdtiRDe6dy3wN4mALo-t7jKTeh_DsJAQ4',
    appId: '1:16569379979:android:545f83feef9d1f022c388e',
    messagingSenderId: '16569379979',
    projectId: 'aqsa-b0bd2',
    storageBucket: 'aqsa-b0bd2.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWIX7YUUl6HxtxIQQInuPTgbxgLtk0tAQ',
    appId: '1:16569379979:web:4f35a760ca0c3ec12c388e',
    messagingSenderId: '16569379979',
    projectId: 'aqsa-b0bd2',
    authDomain: 'aqsa-b0bd2.firebaseapp.com',
    storageBucket: 'aqsa-b0bd2.firebasestorage.app',
  );
}
